chore(ilp): Handle trying to convert ILP strings into non STRING colu…
questdb/questdb pull request #1029
Opened 2021-05-17 09:15 UTC by patrickSpaceSurfer

…mns more gracefully

2021-05-17 09:41 UTC, ideoma commented
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

2021-05-17 12:04 UTC, patrickSpaceSurfer commented
> #### [PR Coverage check]
> 
> heart_eyes **pass** : 0 / 0 (0%)

2021-05-17 12:04 UTC, patrickSpaceSurfer commented
> #### [PR Coverage check]
> 
> heart_eyes **pass** : 0 / 0 (0%)

I have no idea what this means?

2021-05-17 12:28 UTC, ideoma commented
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

2021-05-17 12:40 UTC, bluestreak01 requested changes
small changes pls

2021-05-17 12:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
> +                                    throw CairoException.instance(0).put("line protocol STRING cannot be inserted into column type ").put(ColumnType.nameOf(colType)).put(") [entityType=")
logging `colType` twice

2021-05-17 12:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java
> +                            switch (colType) {
if - else perhaps?

2021-05-17 14:31 UTC, ideoma commented
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

2021-05-17 16:39 UTC, ideoma commented
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

2021-05-17 17:45 UTC, bluestreak01 approved these changes

2021-05-18 09:50 UTC, merged

2021-05-20 18:08 UTC, ideoma commented
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

2026-05-27 12:57 UTC, bluestreak01 approved these changes
Approve. Clean test-only fix — unique dummy-table names per test eliminate the log-barrier race on the reused server.