Fix/count agg function empty or fails
questdb/questdb pull request #1041
Opened 2021-05-20 14:26 UTC by ideoma

2021-05-20 14:47 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 76 / 90 (84.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|3|8|37.50%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|4|10|40.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|6|7|85.71%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|16|17|94.12%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtIntFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-20 16:35 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 89 / 90 (98.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtIntFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 08:54 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 90 / 90 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtIntFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/GroupByUtils.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 09:18 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 93 / 93 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtIntFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|17|17|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 09:36 UTC, bluestreak01 requested changes

2021-05-21 09:36 UTC, bluestreak01 commented on core/src/test/java/io/questdb/cairo/RecordCursorPrinter.java
> +            sink.put(":").put(ColumnType.nameOf(m.getColumnType(i)));
can be ':'

2021-05-21 09:36 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/groupby/vect/SumTimestampVectorAggregateFunction.java
> +    public void aggregate(long pRosti, long keyAddress, long valueAddress, long valueAddressSize, int columnSizeHint, int workerId) {
parameter name continuity

2021-05-21 10:32 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 92 / 92 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/lt/LtIntFunctionFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 10:51 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 91 / 91 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 11:44 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 125 / 125 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 12:58 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 117 / 117 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 13:31 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 125 / 125 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunction.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountLong256GroupByFunction.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunction.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunction.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountSymbolGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/MaxFloatGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstFloatGroupByFunction.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/GroupByFunction.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/FirstCharGroupByFunction.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/LastCharGroupByFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/CountStringGroupByFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/IntFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|2|2|100.00%|

2021-05-21 14:14 UTC, bluestreak01 approved these changes

2021-05-21 14:33 UTC, merged