NULL should be variant type instead of always assuming STRING
questdb/questdb pull request #1063
Opened 2021-05-25 21:34 UTC by marregui

For issue: https://github.com/questdb/questdb/issues/973

2021-05-25 21:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb?pullRequest=1063) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb?pullRequest=1063) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb?pullRequest=1063) it.</sub>

2021-06-04 17:31 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 87 / 89 (97.75%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/cairo/NullColumn.java|14|15|93.33%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToShortFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InSymbolFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/AbstractEntityCastFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/CompactMapRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToFloatFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToByteFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToDoubleFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InStrFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToIntFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToDateFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|40|40|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/NullFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToCharFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToStrFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/ContiguousVirtualMemory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/Function.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastBooleanToLongFunctionFactory.java|1|1|100.00%|

2021-06-09 11:33 UTC, ideoma requested changes
This is intersting and good approach. I'd request you search for `cast(null as ` in tests and add similar test without `cast`, there are quite few of those already

2021-06-09 11:33 UTC, ideoma commented on core/src/test/java/io/questdb/griffin/SqlCompilerTest.java
> +            Assert.fail();
This should not fail, null should not be treated as a STRING but as a LONG here, ideally... Or put a comment that it's not done yet

2021-06-09 11:33 UTC, ideoma commented on core/src/test/java/io/questdb/griffin/InsertNullTest.java
> +                        String.format("insert into x select cast(null as %s) from long_sequence(%d)", type[0], NULL_INSERTS),
We don't want the user to cast null to the column type, again ideally...

2021-06-09 16:41 UTC, marregui commented
Hi @ideoma thank you for the review!
I am trying a different approach in a parallel branch, not pushed, where I explore adding a new `ColumnType` for NULL.
Technically, null is not a type, rather the absence of value for the supported types. However I would like to explore that avenue as well, for comparison. I will amend this PR also, to incorporate the feedback.

Thank you again!

2021-07-02 07:08 UTC, Alexis1956 commented
I didn't do anything wrong but you trying to kill me and set me up is wrong. Stop it now or I call the law on you all. Game over. And give me back my money. Or go to jail. And I didn't break anything but you did. I'm done being nice. And you didn't have my permission to sue ny in my name.

2021-07-06 10:06 UTC, bluestreak01 commented
the other PR is better!

2021-07-06 10:06 UTC, closed without merging