Implement LatestByIndexed on cpp side
questdb/questdb pull request #1084
Opened 2021-06-03 15:00 UTC by eugenels

2021-06-03 15:19 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 67 / 137 (48.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|20|48|41.67%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|20|39|51.28%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|11|19|57.89%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|10|10|100.00%|

2021-06-03 17:56 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 67 / 137 (48.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|20|48|41.67%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|20|39|51.28%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|11|19|57.89%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|10|10|100.00%|

2021-06-03 18:34 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 67 / 137 (48.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|20|48|41.67%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|20|39|51.28%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|11|19|57.89%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|10|10|100.00%|

2021-06-03 19:21 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 119 / 137 (86.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|10|10|100.00%|

2021-06-03 20:07 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 116 / 134 (86.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|

2021-06-04 15:43 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 116 / 134 (86.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|

2021-06-04 16:50 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 116 / 134 (86.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|6|8|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|16|19|84.21%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|

2021-06-04 19:11 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 92 / 143 (64.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|20|48|41.67%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|20|39|51.28%|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|8|10|80.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|7|8|87.50%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|

2021-06-08 13:46 UTC, bluestreak01 requested changes

2021-06-08 13:46 UTC, bluestreak01 commented on core/src/main/c/share/bitmap_index_utils.cpp
> +                rows[k] = ((int64_t) partition_index << 44) + unindexed_null_count;
we should perhaps refactor a helper method here, which creates rowid, perhaps an abstract type ?

2021-06-08 13:46 UTC, bluestreak01 commented on core/src/main/c/share/bitmap_index_utils.cpp
> +                int64_t local_row_id = values[last_vblock_offset / 8 + cell_index];
is there a way to get c++ do this arithmetic ?

2021-06-11 11:33 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 0 / 147 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|0|10|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|0|48|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|0|39|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|0|7|00.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|0|12|00.00%|

2021-06-11 16:48 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 147 (99.32%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|12|12|100.00%|

2021-06-14 11:04 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 147 (99.32%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|12|12|100.00%|

2021-06-14 12:35 UTC, bluestreak01 approved these changes

2021-06-14 12:46 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 147 (99.32%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|12|12|100.00%|

2021-06-14 13:45 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 146 / 147 (99.32%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByArguments.java|18|19|94.74%|
|:large_blue_circle:|io/questdb/std/BitmapIndexUtilsNative.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|48|48|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexFwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexBwdNullReader.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|39|39|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/std/DirectLongList.java|12|12|100.00%|

2021-06-14 15:09 UTC, merged