Accept GeoHash literals and constant functions
questdb/questdb pull request #1307
Opened 2021-09-10 11:19 UTC by eugenels

2021-09-10 11:47 UTC, ideoma approved these changes
Looks good. We will probably need another pass to accept Bind Variables

2021-09-10 11:47 UTC, ideoma commented on core/src/main/java/io/questdb/griffin/WhereClauseParser.java
> +                if (token.charAt(1) != '#') {
minor: can be `if (isCharsPrefix)`

2021-09-10 11:49 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 85 / 88 (96.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|59|62|95.16%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 11:52 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 85 / 88 (96.59%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|59|62|95.16%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 13:23 UTC, eugenels commented on core/src/main/java/io/questdb/griffin/WhereClauseParser.java
> +                if (token.charAt(1) != '#') {
updated

2021-09-10 14:00 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 80 / 83 (96.39%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|54|57|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 14:08 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 80 / 83 (96.39%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|54|57|94.74%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 14:28 UTC, bluestreak01 requested changes

2021-09-10 14:28 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/WhereClauseParser.java
> +                throw SqlException.$(inArg.position, "GeoHash const function expected");
function must be closed otherwise it could cause memory leak

2021-09-10 15:13 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 82 (96.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|53|56|94.64%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 15:42 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 82 (96.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|53|56|94.64%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 16:04 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 82 (96.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|53|56|94.64%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 16:19 UTC, marregui reviewed
`select * from pos latest by uuid where time in '2021-05-11' and hash within ('z', 'b')`

hehe, no longer possible to drop a string instead of a geohash. In other places we are more lenient, for instance in eq comparison we cast the str to a geohash. Would it make sense to allow this here? I do not have strong opinions in here.

2021-09-10 17:12 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 82 (96.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|53|56|94.64%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-10 17:20 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 82 (96.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|53|56|94.64%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-11 07:44 UTC, bluestreak01 approved these changes

2021-09-11 08:03 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 82 (96.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|53|56|94.64%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-11 08:08 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 79 / 82 (96.34%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/WhereClauseParser.java|53|56|94.64%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedFilteredRecordCursorFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/ColumnType.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GeoHashes.java|9|9|100.00%|

2021-09-11 20:54 UTC, merged