feat: add base64 function to encode binary data
questdb/questdb pull request #1355
Opened 2021-09-24 16:51 UTC by eugenels

2021-09-24 17:16 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 10 / 33 (30.30%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|10|33|30.30%|

2021-09-24 17:25 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 10 / 33 (30.30%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|10|33|30.30%|

2021-09-24 17:29 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 10 / 33 (30.30%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|10|33|30.30%|

2021-09-27 11:13 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 26 (96.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/std/Chars.java|20|20|100.00%|

2021-09-27 11:15 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 26 (96.15%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/std/Chars.java|20|20|100.00%|

2021-09-27 12:35 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 33 (84.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|8|13|61.54%|
|:large_blue_circle:|io/questdb/std/Chars.java|20|20|100.00%|

2021-09-27 12:37 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 33 (84.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|8|13|61.54%|
|:large_blue_circle:|io/questdb/std/Chars.java|20|20|100.00%|

2021-09-27 14:55 UTC, bluestreak01 requested changes

2021-09-27 14:55 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java
> +            throw SqlException.$(argPositions.getQuick(1), "maxLength has to be greater than 0");
could we also limit max length from top, perhaps to configuration value to make sure system cannot be abused ?

2021-09-27 14:55 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java
> +        if (func.isConstant()) {
this is really not necessary, SQL optimiser does this for you

2021-09-27 15:34 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 28 / 33 (84.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|8|13|61.54%|
|:large_blue_circle:|io/questdb/std/Chars.java|20|20|100.00%|

2021-09-28 11:34 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 30 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|

2021-09-28 11:35 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 30 / 30 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|20|20|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bin/Base64FunctionFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|

2021-09-28 14:54 UTC, bluestreak01 approved these changes

2021-09-28 14:55 UTC, merged