chore(o3): make column memory size configurable
questdb/questdb pull request #1373
Opened 2021-09-30 11:29 UTC by eugenels

2021-09-30 11:48 UTC, marregui submitted a review, later dismissed
LGTM

would it be worth adding an entry in `server.conf`:
```
#cairo.o3.column.memory.size=16777216
```

2021-09-30 11:55 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|

2021-09-30 12:03 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|

2021-09-30 12:37 UTC, bluestreak01 requested changes

2021-09-30 12:37 UTC, bluestreak01 commented on core/src/main/java/io/questdb/PropServerConfiguration.java
> +            this.o3ColumnMemorySize = Numbers.ceilPow2(getIntSize(properties, env, "cairo.o3.column.memory.size", 16 * Numbers.SIZE_1MB));
`ceilPow2` is incorrect. We have `Files.ceilPageSize()`

2021-09-30 12:38 UTC, bluestreak01 commented
we also need to configure append page size for table writer

2021-09-30 14:33 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

2021-09-30 14:35 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

2021-10-01 08:43 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

2021-10-01 08:46 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

2021-10-01 09:28 UTC, ideoma commented
Related to #1369

2021-10-01 10:08 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

2021-10-01 10:17 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|

2021-10-01 18:14 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 72 / 94 (76.60%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|10|11|90.91%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-01 18:18 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 74 / 96 (77.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-01 18:22 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 74 / 96 (77.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-01 20:56 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 74 / 96 (77.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-01 21:05 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 74 / 96 (77.08%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|11|12|91.67%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-02 09:00 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 91 (80.22%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|16|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-02 09:02 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 94 (77.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-02 09:07 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 94 (77.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-02 19:20 UTC, bluestreak01 approved these changes

2021-10-03 21:36 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 94 (77.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-03 21:49 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 73 / 94 (77.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|0|19|00.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|23|25|92.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/SymbolCache.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapReaderImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/Files.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolColumnIndexer.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableBlockWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/SymbolMapWriter.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/cairo/AbstractIndexReader.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReader.java|1|1|100.00%|

2021-10-04 12:51 UTC, merged

2021-10-04 12:53 UTC, marregui approved these changes
LGTM