fix(cairo): o3 copy to use index block capacity
questdb/questdb pull request #1548
Opened 2021-11-09 21:17 UTC by ideoma

When Out of Order insert happens and index is re-written the index file is initialised with minimum Index Block Capacity equals to 4. This kills performance of Out of Order index rewrite on the partition since block capacity of 4 forces to add a new block for every 4 values. 

It is especially painful when there are few distinct values of the column with hundred thousands of values.

The fix makes sure that when index is re-written during O3 insert the most up to date value of Index Block Capacity is used from table metadata

2021-11-09 21:45 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 17 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|3|3|100.00%|

2021-11-09 21:45 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 17 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|3|3|100.00%|

2021-11-09 21:49 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 17 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|3|3|100.00%|

2021-11-10 00:22 UTC, bluestreak01 requested changes

2021-11-10 00:22 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/O3PartitionJob.java
> +                final boolean indexBlockCapacity = metadata.isColumnIndexed(i);
confusing naming

2021-11-10 00:22 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/O3PartitionJob.java
> +                if (indexBlockCapacity) {
same

2021-11-10 00:22 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/O3PartitionJob.java
> +                                indexValueCapacity,
inconsistent parameter name

2021-11-10 00:22 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/O3CopyJob.java
> +            int indexValueCapacity
inconsistent parameter name

2021-11-10 00:23 UTC, bluestreak01 commented
it would also be good to harmonise `initKeyMemory` parameter name with variable names that are passed to that parameter

2021-11-10 00:32 UTC, ideoma commented on core/src/main/java/io/questdb/cairo/O3PartitionJob.java
> +                if (indexBlockCapacity) {
ok

2021-11-10 00:33 UTC, ideoma commented on core/src/main/java/io/questdb/cairo/O3PartitionJob.java
> +                                indexValueCapacity,
ok

2021-11-10 00:34 UTC, ideoma commented on core/src/main/java/io/questdb/cairo/O3CopyJob.java
> +            int indexValueCapacity
ok

2021-11-10 00:43 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|1|1|100.00%|

2021-11-10 00:50 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|1|1|100.00%|

2021-11-10 00:58 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|1|1|100.00%|

2021-11-10 01:03 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|1|1|100.00%|

2021-11-10 01:08 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 23 / 23 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3OpenColumnTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCMARWImpl.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/BitmapIndexWriter.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/tasks/O3CopyTask.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionJob.java|1|1|100.00%|

2021-11-10 07:08 UTC, bluestreak01 approved these changes

2021-11-10 07:09 UTC, merged