fix(sql) Column alias 'time' does not work
questdb/questdb pull request #1602
Opened 2021-11-21 20:28 UTC by mkaruza

When statement is parsed it is expected that complete part `with time zone` should be
skipped.

2021-11-21 20:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb?pullRequest=1602) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb?pullRequest=1602) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb?pullRequest=1602) it.</sub>

2021-11-23 14:31 UTC, ideoma requested changes
Please add unit tests to support that it fixes the issue and does not introduce regression in similar scenarios

2021-11-23 21:32 UTC, mkaruza commented
@ideoma updated commit with test cases

2021-11-23 23:12 UTC, bluestreak01 submitted a review, later dismissed

2021-11-25 10:30 UTC, mkaruza commented on core/src/test/java/io/questdb/griffin/SimpleTableTest.java
> +            assertSql("select timestamp with time zone from t;", expected2);
@ideoma you are correct this should be syntax error. I have overlooked how postgres is using this. I have addressed this issue and updates tests.

2021-11-25 14:03 UTC, ideoma approved these changes

2021-11-26 10:57 UTC, merged