feat(sql) SQL for bulk insert
questdb/questdb pull request #1603
Opened 2021-11-21 20:29 UTC by mkaruza

Support for multiple row inserts.

2021-11-21 20:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb?pullRequest=1603) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb?pullRequest=1603) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb?pullRequest=1603) it.</sub>

2021-11-21 21:31 UTC, bluestreak01 commented
thank you @mkaruza 👍 

However the implemented functionality requires way more tests that is offered in the PR

2021-11-22 21:51 UTC, mkaruza commented
Added new test cases

2021-11-23 22:40 UTC, bluestreak01 requested changes
In addition to comments above, the following syntax problems exist:

```sql
create table x(a int, b int, c int);
```

```sql
-- expected error got 1 row + success
insert into x values ((1,2,3), (1,2), (3,4,5));
```

```sql
-- insert executes when syntax error is expected
insert into x values (1,3,5),(3,4,0),;
```

```sql
-- error text is factually incorrect, error position is incorrect
insert into x values (1,3,5,6),(3,4,0), (5,6,9);
```

2021-11-23 22:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCompiler.java
> +                                    "not enough values [expected=").put(columnCount).put(", actual=").put(values.size())
this error message is factually incorrect when row group has more values than target columns

2021-11-23 22:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCompiler.java
> +                                    .put(", row=").put(t+1).put(']');
inconsistent naming row/tuple

2021-11-23 22:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCompiler.java
> +                                    model.getEndOfValuesPosition(),
position does not reflect site of error

2021-11-23 22:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCompiler.java
> +                            }
minor: code formatting

2021-11-23 22:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCompiler.java
> +        int rowTupleCount = model.getRowTupleCount();
inconsistent naming: rowValues/rowTuples/rowValueTuples

2021-11-23 22:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/model/InsertModel.java
> +            for (int t = 0; t < rowValuesTuples.size(); t++) {
loop syntax

2021-11-23 22:40 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCompiler.java
> +                throw SqlException.$(model.getColumnPosition(0), "row value count does not match column count [tuple=" + (i + 1) + "]");
error position is incorrect - should position on tuple with incorrect value count

2021-11-24 14:59 UTC, bluestreak01 approved these changes

2021-11-24 17:05 UTC, merged