fix(cairo): various failures when column sizes are near page size
questdb/questdb pull request #1727
Opened 2021-12-22 16:19 UTC by ideoma

- fixed a failure in column resizing on writer close when var column size is near mapping page size.
- fixed a failure in commit with lag when var column size in lag exceeds o3 memory allocation page size.

2021-12-22 16:49 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-22 16:54 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-22 19:01 UTC, bluestreak01 requested changes

2021-12-22 19:01 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/TableWriter.java
> +                    mem2.jumpTo(pos * Long.BYTES);
the intent behind is to ensure side, "under-jumping" could mean there is no 8 bytes to read after that. The only reason it works is that page size uniquely divisibly by 8 and this doesn't happen or very hard to make happen. Nonetheless logically this is incorrect

2021-12-22 22:58 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 0 / 18 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|0|5|00.00%|

2021-12-22 23:16 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-22 23:18 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 0 / 18 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|0|4|00.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|0|3|00.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|0|5|00.00%|

2021-12-22 23:34 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 11:27 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 11:36 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 18 / 18 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 12:26 UTC, puzpuzpuz submitted a review, later dismissed

2021-12-23 15:16 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 15:17 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 15:23 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 16:32 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 33 / 33 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|18|18|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 16:37 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 16:41 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 31 / 31 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableReaderSelectedColumnRecord.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3CopyJob.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/O3OpenColumnJob.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryCARWImpl.java|5|5|100.00%|

2021-12-23 19:46 UTC, bluestreak01 approved these changes

2021-12-23 19:46 UTC, merged