fix(sql): throw exception if order by expression is not in select list
questdb/questdb pull request #1743
Opened 2021-12-29 11:36 UTC by eugenels

fixes https://github.com/questdb/questdb/issues/1600

2021-12-29 12:06 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-29 12:15 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 12:15 UTC, bluestreak01 requested changes

2021-12-30 12:15 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/O3Test.java
> -                "z order by i,sym,amt",
```
z order by i,sym,amt
```
is equivalent to
```
select * from z order by i,sym,amt
```

therefore the former should still work

2021-12-30 12:43 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 12:51 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 13:35 UTC, bluestreak01 requested changes

2021-12-30 13:35 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/AbstractO3Test.java
>              @Nullable String referenceTableDDL,
in this file, there is unused import

2021-12-30 13:54 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 13:58 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 14:32 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 14:37 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 15:40 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 15:45 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|10|10|100.00%|

2021-12-30 15:53 UTC, bluestreak01 approved these changes

2021-12-30 19:07 UTC, merged