chore(build): remove c++ runtime/stdlib dependency
questdb/questdb pull request #1761
Opened 2022-01-05 14:18 UTC by eugenels

2022-01-05 17:53 UTC, bluestreak01 submitted a review, later dismissed

2022-01-06 16:43 UTC, bluestreak01 requested changes

2022-01-06 16:43 UTC, bluestreak01 commented on core/src/test/java/io/questdb/cairo/AbstractCairoTest.java
> +                return SqlJitMode.JIT_MODE_DISABLED;
Lets get to the bottom of the crash.

For context with JIT enabled this test crashes on JDK17

2022-01-06 22:53 UTC, bluestreak01 requested changes

2022-01-06 22:53 UTC, bluestreak01 commented on core/src/main/c/share/cpprt_overrides.cpp
> +//void* operator new(size_t size) { return malloc(size); }
debris?

2022-01-07 23:49 UTC, bluestreak01 submitted a review, later dismissed

2022-01-08 11:52 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/JitUtil.java|1|1|100.00%|

2022-01-08 12:00 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/JitUtil.java|1|1|100.00%|

2022-01-08 14:02 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/JitUtil.java|1|1|100.00%|

2022-01-08 14:50 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/JitUtil.java|1|1|100.00%|

2022-01-08 15:59 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/JitUtil.java|1|1|100.00%|

2022-01-08 18:50 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|0|1|00.00%|

2022-01-08 19:00 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|1|1|100.00%|

2022-01-09 00:05 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|0|1|00.00%|

2022-01-09 00:14 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|1|1|100.00%|

2022-01-09 01:11 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|1|1|100.00%|

2022-01-09 04:15 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|1|1|100.00%|

2022-01-09 07:47 UTC, ideoma commented
#### [PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|0|1|00.00%|

2022-01-09 07:53 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/jit/CompiledFilter.java|1|1|100.00%|

2022-01-09 11:49 UTC, bluestreak01 approved these changes

2022-01-09 11:50 UTC, merged