fix(sql): partitioning without designated timestamp should not be possible
questdb/questdb pull request #1844
Opened 2022-01-31 11:02 UTC by puzpuzpuz

A continuation of #1760 (see #1770 to learn why we had to revert this)

2022-01-31 11:33 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-01-31 11:37 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-01-31 13:22 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-01-31 14:53 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-01-31 14:59 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-01-31 19:08 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-01-31 19:14 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-01 06:44 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-01 06:51 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-01 07:04 UTC, puzpuzpuz commented
Citation from #1770:
> I will investigate further what exactly caused the crash, but for now the suspicion is that an unordered field was set as designated timestamp, which caused O3 to go wild on memory writes.

I've checked the modified tests and nothing looks suspicious. Test execution times also didn't change. I've run CI four times in a row and didn't notice any CI crashes/failures. So, this one may be ready to go.

2022-02-01 14:43 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-01 14:59 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-01 15:31 UTC, bluestreak01 requested changes

2022-02-01 15:31 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/O3CommitLagTest.java
> +        sql = "create table y as (select * from x where i<=150) timestamp(ts) partition by DAY";
This is very risky. When we move to async filter execution, records might come out of order. `timestamp(ts)` does not enforce order, so there is a risk of creating table with wrong order of records and declared timestamp. O3 will crash.

2022-02-01 16:19 UTC, bluestreak01 approved these changes

2022-02-01 16:37 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-01 19:22 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-02 11:43 UTC, bluestreak01 commented
@puzpuzpuz this is what we observed before, CI crash

2022-02-02 11:53 UTC, puzpuzpuz commented
> @puzpuzpuz this is what we observed before, CI crash

@bluestreak01 
The recent Windows CI crash seems to be related with `LineTcpReceiverFuzzTest#testLoad` and system-wise OOM:
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 941856 bytes for Chunk::new
# An error report file with more information is saved as:
# D:\a\1\s\core\hs_err_pid5668.log
```

Was it the same when these changes weren't reverted yet?

2022-02-02 13:59 UTC, bluestreak01 commented
I don't remember in fact :( Regardless, I think it is risky to merge considering this is a first instance of a crash here since ILP fixes

2022-02-02 14:00 UTC, bluestreak01 requested changes
We will have to understand the crash before merging

2022-02-02 14:00 UTC, puzpuzpuz commented
> I don't remember in fact :( Regardless, I think it is risky to merge considering this is a first instance of a crash here since ILP fixes

OK, let's see if the same crash shows up on other branches. It may be unrelated to the changes after all.

2022-02-02 14:06 UTC, bluestreak01 commented
> OK, let's see if the same crash shows up on other branches. It may be unrelated to the changes after all.

Cool, lets trigger other branches manually if need be.

2022-02-02 18:53 UTC, ideoma commented
I saw `Native memory allocation (malloc) failed to allocate` on other builds without this change on Windows. @glasstiger and I came to conclusion that it was genuine OS out of memory.

2022-02-02 19:13 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-04 00:24 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|

2022-02-04 01:40 UTC, bluestreak01 approved these changes

2022-02-04 01:40 UTC, merged

2022-02-04 06:35 UTC, puzpuzpuz commented
@kocko many thanks for the contribution! Sorry for the back-and-forth with merging your patch.