feat(sql): date_trunc() implementation
questdb/questdb pull request #1885
Opened 2022-02-13 17:52 UTC by jerrinot

closes #1818

It adds support for truncating timestamps. 
Intervals are not supported at the moment. I'm not sure if QuestDB supports the Postgres Interval type at all. Any pointer is much appreciated.

2022-02-13 17:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb?pullRequest=1885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb?pullRequest=1885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb?pullRequest=1885) it.</sub>

2022-02-14 08:44 UTC, bluestreak01 requested changes

2022-02-14 08:44 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/engine/functions/date/DateTruncFunctionFactoryTest.java
> +        assertTimestamp("SELECT DATE_TRUNC('week',          TIMESTAMP '2017-03-13T02:09:30.111111Z') as truncated","2017-03-13T00:00:00.000000Z");
Although test coverage is very good, I would expect to see edge case tests. Specifically around newly added date arithmetic.

2022-03-21 16:59 UTC, marregui commented
hi @jerrinot, I hope you are well!

I was wondering what the status of the PR is, are you going to continue to work on it?.
Thank you in advance, best regards.

2022-04-04 07:05 UTC, jerrinot commented on core/src/test/java/io/questdb/std/datetime/microtime/TimestampsBruteForceTest.java
> +    public void testFloorSS_bruteforce() {
please ginote a left-over name

2022-04-04 08:06 UTC, jerrinot commented
@marregui I pushed an idea of randomized brute-force tests, the idea comes from @bluestreak01 
It's not complete yet, just an idea. please let me know what do you think.

2022-04-07 08:58 UTC, marregui commented
hola @jerrinot would it make sense to reopen the PR from a branch off questdb/master and take the review there?

brute force meaning exhaustive with the whole domain for the function would take an infinite amount of time.

2022-04-07 09:06 UTC, jerrinot commented
@marregui: sure, I'll push my branch to the upstream repo. 

indeed, it's a compromise between test duration and the confidence the test gives. the alternative is to hard-code a few selected "edge-case" timestamps and test just that. this assumes you select the right edge-cases. and if you don't then you may learn about it only when it's too late. that is the idea anyway, my opinion is not overly strong on this.

2022-04-07 15:08 UTC, jerrinot commented
closing in favour of https://github.com/questdb/questdb/pull/2017

2022-04-07 15:08 UTC, closed without merging