fix: handing corrupt _txn file in Mig620
questdb/questdb pull request #1933
Opened 2022-03-07 13:54 UTC by ideoma

2022-03-07 14:10 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 8 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|6|8|75.00%|

2022-03-07 19:56 UTC, bluestreak01 requested changes

2022-03-07 19:56 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/mig/Mig620.java
> +                throw CairoException.instance(0).put("corrupt _txn file, partitions are not ordered at ").put(path.trimTo(pathLen));
path.trimTo() does not ensure string is zero-terminated

2022-03-07 22:29 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 8 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|6|8|75.00%|

2022-03-08 10:01 UTC, bluestreak01 approved these changes

2022-03-08 10:17 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 8 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|6|8|75.00%|

2022-03-08 10:29 UTC, merged