fix(ilp): tolerate space symbol at the line end
questdb/questdb pull request #1940
Opened 2022-03-09 12:54 UTC by ideoma

2022-03-09 13:08 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|2|2|100.00%|

2022-03-09 19:05 UTC, bluestreak01 requested changes
PR requires description of problem, so that user reading changelog can understand what is fixed.

2022-03-10 12:03 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpParser.java|2|2|100.00%|

2022-03-10 12:12 UTC, bluestreak01 approved these changes

2022-03-10 13:16 UTC, merged