fix(pgwire): fix persistent function parser issue
questdb/questdb pull request #1997
Opened 2022-03-31 10:55 UTC by bziobrowski

Also - disconnect on unexpected errors to fix jdbc client lockup .

It's probably better to report such errors back to client but : 
1. simply returning "internal server error" in cursor phases doesn't seem to work and client still hangs
2. disconnecting should 'fix' potential server state corruption (as was the case with function parser)

2022-03-31 11:17 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|

2022-03-31 15:35 UTC, bluestreak01 requested changes

2022-03-31 15:35 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/FunctionParserErrorTest.java
> +                    null, null, true, false, true);
We need `Assert.fail()` here, otherwise test will also pass when there is no exception

2022-03-31 15:35 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/FunctionParserErrorTest.java
> +        } catch (SqlException e) {
same, need fail()

2022-03-31 15:35 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/FunctionParserErrorTest.java
> +        } catch (SqlException e) {
same, need fail()

2022-03-31 16:09 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGWireServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|2|2|100.00%|

2022-04-01 15:35 UTC, bluestreak01 approved these changes

2022-04-01 15:35 UTC, merged