fix: tolerate missing partition folders in 6.2.1 -> 6.3 migration
questdb/questdb pull request #2114
Opened 2022-05-10 16:39 UTC by ideoma

When last partition exists in `_txn` file but does not exist on disk (perhaps QuestDB was hard aborted) Mig620 fails.

The fix will tolerate missing partitions, including missing last partition assuming column presence in the missing partition is the same as in the proceeding partition.

2022-05-10 17:53 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 17 / 19 (89.47%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|17|19|89.47%|

2022-05-10 19:49 UTC, bluestreak01 requested changes

2022-05-11 14:22 UTC, ideoma commented on core/src/test/java/io/questdb/test/tools/TestUtils.java
> +    public static void copyDirectory(Path from, Path to, int dirMode) throws IOException {
done in https://github.com/questdb/questdb/pull/2114/commits/1b73cf180b3bc9f9935cbc2e379f3069ba774059

2022-05-11 14:49 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 32 (90.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|17|19|89.47%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|12|13|92.31%|

2022-05-11 16:34 UTC, bluestreak01 approved these changes

2022-05-11 17:33 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 32 (90.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|17|19|89.47%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|12|13|92.31%|

2022-05-11 18:11 UTC, marregui submitted a review, later dismissed
LGTM

2022-05-11 18:14 UTC, marregui commented on core/src/test/java/io/questdb/test/tools/TestUtils.java
> +import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
not used either :)

2022-05-11 18:15 UTC, ideoma commented on core/src/test/java/io/questdb/test/tools/TestUtils.java
> +import java.nio.file.FileSystems;
```suggestion
```

2022-05-11 19:46 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 32 (90.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|17|19|89.47%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|12|13|92.31%|

2022-05-12 09:01 UTC, ideoma commented on core/src/test/java/io/questdb/test/tools/TestUtils.java
> +import java.nio.file.FileSystems;
done

2022-05-12 09:01 UTC, ideoma commented on core/src/test/java/io/questdb/test/tools/TestUtils.java
> +import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
done

2022-05-12 09:09 UTC, marregui approved these changes
LGTM

2022-05-12 09:23 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 29 / 32 (90.62%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/mig/Mig620.java|17|19|89.47%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|12|13|92.31%|

2022-05-12 14:01 UTC, merged