Added new translation
questdb/questdb pull request #2215
Opened 2022-06-12 09:06 UTC by 1998code

Added new zh-hk translation
Fixed incorrect languages order in zh-cn and line breaking in zh-cn and ar-dz.

2022-06-12 09:08 UTC, 1998code commented
Thanks :)

2022-06-14 13:25 UTC, amyshwang requested changes
Thank you for the translation. I have made some suggestions mainly based on usage in Taiwan - I hope it makes sense.

2022-06-14 13:40 UTC, 1998code commented on i18n/README.zh-hk.md
> +  讀[貢獻指南](https://github.com/questdb/questdb/blob/master/CONTRIBUTING.md)。
Fixed :)

2022-06-14 13:40 UTC, 1998code commented on i18n/README.zh-hk.md
> +我們總是樂於接受對項目的貢獻，無論是源代碼、文檔、錯誤報告、功能請求還是反饋。如
Changed :)

2022-06-14 13:41 UTC, 1998code commented on i18n/README.zh-hk.md
> +  或是反饋問題。
Changed :)

2022-06-14 13:41 UTC, 1998code commented on i18n/README.zh-hk.md
> +[QuestDB 下載頁面](https://questdb.io/get-questdb/) 提供二進制文件的直接下載，並提供其他安裝和部署方法的詳細信息。
Changed :)

2022-06-14 13:41 UTC, 1998code commented on i18n/README.zh-hk.md
> +執行時間。
Okay :)

2022-06-14 13:41 UTC, 1998code commented
Thanks @amyshwang :)

2022-06-14 19:23 UTC, merged