fix: don't overwrite passwords and setting files on start/reboot
questdb/questdb pull request #2271
Opened 2022-06-24 17:13 UTC by mariusgheorghies

2022-06-24 18:22 UTC, bluestreak01 requested changes

2022-06-24 18:22 UTC, bluestreak01 commented on pkg/ami/marketplace/scripts/1-per-boot.sh
> +  cp /etc/questdb/server.conf /var/lib/questdb/conf/server.conf_new
i think we can skip copying this file if it exists, we don't usually bring anything useful to user via that file

2022-06-27 11:09 UTC, ideoma commented
Fixes #2199

2022-06-27 16:24 UTC, bluestreak01 approved these changes

2022-06-27 16:24 UTC, merged