fix(sql): add single quotes escaping within string literals
questdb/questdb pull request #2506
Opened 2022-09-06 14:46 UTC by bziobrowski

Fixes #2309

2022-09-06 15:02 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|6|6|100.00%|

2022-09-07 08:13 UTC, marregui approved these changes
LGTM

2022-09-07 10:56 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|6|6|100.00%|

2022-09-08 00:33 UTC, bluestreak01 requested changes

2022-09-08 00:33 UTC, bluestreak01 commented on core/src/main/java/io/questdb/std/GenericLexer.java
> +                        if (hasNext() && content.charAt(_pos) == '\'') {
`hasNext()` call is quite heavy in this context, it can be replaced with `_pos < _len`. In fact `while(hasNext())` is also too heavy

2022-09-08 14:56 UTC, bluestreak01 approved these changes

2022-09-08 15:12 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Chars.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/constants/StrConstant.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/std/GenericLexer.java|7|7|100.00%|

2022-09-08 16:25 UTC, merged