fix(sql): reduce memory utilization of cursor factories
questdb/questdb pull request #2539
Opened 2022-09-21 12:04 UTC by bziobrowski

This PR pushes most native memory allocations from factories to cursors .
Instead of being kept all the time (e.g. when factory is in cache), they're released on cursor.close()
and re-allocated on factory.getCursor(). 

Note: some allocations can't be cleared completely on cursor.close() because it'd break the factory, e.g.  join metadata map .

2022-09-21 15:05 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 193 / 202 (95.54%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|5|9|55.56%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursorFactory.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordTreeChain.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryPages.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecordChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillPrevRecordCursor.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|2|2|100.00%|

2022-09-21 17:09 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 193 / 202 (95.54%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|5|9|55.56%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursorFactory.java|3|4|75.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordTreeChain.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryPages.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecordChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillPrevRecordCursor.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|2|2|100.00%|

2022-09-23 12:51 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 194 / 202 (96.04%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|5|9|55.56%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordTreeChain.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryPages.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecordChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillPrevRecordCursor.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|2|2|100.00%|

2022-09-23 12:52 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/map/FastMap.java
> +        this(pageSize, keyTypes, valueTypes, keyCapacity, loadFactor, hashFunction, maxResizes, -1);
nit: we could pass actual tag we want and remove conditionals from the main constructor

2022-09-23 13:27 UTC, bluestreak01 requested changes

2022-09-23 13:27 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java
> +        if (cursor != null) {
`Misc.free()`

2022-09-23 13:27 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java
> +            if (cursor != null) {
`Misc.free()`

2022-09-23 13:27 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java
> +        if (base != null) {
```
base = Misc.free(base);
baseRecord = null;
```

2022-09-23 14:54 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 190 / 197 (96.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|5|8|62.50%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordTreeChain.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryPages.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecordChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillPrevRecordCursor.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|2|2|100.00%|

2022-09-23 16:04 UTC, amunra approved these changes
Lookin' good.

The `Reallocatable` interface threw me off in terms of naming, but there's no reason why this can't be done as a small follow-up PR.

2022-09-23 16:04 UTC, amunra commented on core/src/main/java/io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunction.java
> +        mapValue.putDouble(valueIndex, Double.NaN);
Looks like this is a bugfix for `testSampleFillValueListWithNullAndPrev`. Nice.

2022-09-23 17:39 UTC, bluestreak01 approved these changes

2022-09-23 17:57 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 190 / 197 (96.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursorFactory.java|5|8|62.50%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/HashOuterJoinRecordCursorFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordTreeChain.java|5|6|83.33%|
|:large_blue_circle:|io/questdb/griffin/engine/join/AsOfJoinRecordCursorFactory.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursorFactory.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryPages.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/AsyncFilteredRecordCursor.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeLongTreeChain.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/RecordChain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/AbstractRedBlackTree.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LimitedSizeSortedLightRecordCursor.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/groupby/AvgDoubleGroupByFunction.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedLightRecordCursor.java|9|9|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/JoinRecordMetadata.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/LongTreeChain.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/CachedAnalyticRecordCursorFactory.java|28|28|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillNoneRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/std/MemoryTag.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/SortedRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/vect/GroupByRecordCursorFactory.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cairo/map/FastMap.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillValueRecordCursor.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/AbstractSampleByFillRecordCursorFactory.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByFillPrevRecordCursor.java|12|12|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/join/LtJoinLightRecordCursorFactory.java|2|2|100.00%|

2022-09-23 18:17 UTC, merged