[Documentation] Add the italian translation
questdb/questdb pull request #2589
Opened 2022-10-05 12:24 UTC by TheZal

This Pull Request close the issue #2586

2022-10-05 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb?pullRequest=2589) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb?pullRequest=2589) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb?pullRequest=2589) it.</sub>

2022-10-05 15:59 UTC, amunra requested changes
Ho richesto solo dei piccoli cambiamenti.
Tutti molto minori.

Se vuoi puoi anche aggiungere una nota nella sezione di chiedere support che possiamo essere contattati anche direttamente in italiano :-)

Grazie mille!

2022-10-05 15:59 UTC, amunra commented on i18n/README.it-it.md
> +versione QuestDb ed un semplice dataset :
ed un semplice dataset :
->
e di datasets di esempio:

2022-10-05 15:59 UTC, amunra commented on i18n/README.it-it.md
> +La [pagina di download QuestDB](https://questdb.io/get-questdb/) fornisce il download diretto dei file binari
pagina di download QuestDB
->
pagina di download di QuestDB

2022-10-05 15:59 UTC, amunra commented on i18n/README.it-it.md
> +- [Stack Overflow:](https://stackoverflow.com/questions/tagged/questdb) cerca soluzioni a problemi comuni
Punto a fine frase.

2022-10-05 15:59 UTC, amunra commented on i18n/README.it-it.md
> +- Per dettagli per buildare QuestDB
buildare -> creare build di

2022-10-05 15:59 UTC, amunra commented on i18n/README.it-it.md
> +Ogni contributo di ogni tipo è il benvenuto!
Ogni contributo di ogni tipo è il benvenuto!
->
Contributi di qualsiasi tipo sono sempre benvenuti!

2022-10-05 18:58 UTC, AndreaCAnastasi commented on i18n/README.it-it.md
> +Queste estensioni permettono facilmente di collegare dati da molteplici sorgenti
sorgenti -> fonti

2022-10-06 10:42 UTC, amunra approved these changes
Grande!

2022-10-06 10:50 UTC, merged