fix(sql): avoid unexpected errors when over() clause for analytic function is missing
questdb/questdb pull request #2657
Opened 2022-10-19 04:59 UTC by puzpuzpuz

2022-10-19 05:17 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 15 / 15 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RankFunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/AnalyticContextImpl.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

2022-10-19 15:48 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 48 (85.42%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RankFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/AnalyticContextImpl.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

2022-10-21 13:01 UTC, bluestreak01 requested changes

2022-10-21 13:08 UTC, puzpuzpuz commented on core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
> -    @Test
`SqlCodeGeneratorTest` is huge, so it's worth splitting it into specific test suites when possible.

2022-10-21 13:12 UTC, bluestreak01 approved these changes

2022-10-21 13:12 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/SqlCodeGeneratorTest.java
> -    @Test
cool 👍

2022-10-21 13:29 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 48 (85.42%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RowNumberFunctionFactory.java|17|23|73.91%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/analytic/RankFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlExecutionContextImpl.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/analytic/AnalyticContextImpl.java|11|11|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|5|5|100.00%|

2022-10-21 13:47 UTC, merged