chore(docs): Ukrainian readme translation
questdb/questdb pull request #2660
Opened 2022-10-19 15:13 UTC by bluestreak01

also fixed broken links in other readme(s). Italian was particularly wonky :)

2022-10-19 15:14 UTC, questdb-butler commented
<!--
  1 failure:  Please update the...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `build`, `ci`, `chore`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 875444b3901bae1cfef21efada8d8c8c3e0555d1
</p>

2022-10-19 15:38 UTC, ideoma requested changes
There is more to it in every sentence, need quite a bit of work and Ukrainian keyboard

2022-10-20 14:37 UTC, eugenels commented on i18n/README.ua-ua.md
> +- [Підручники:](https://questdb.io/tutorial/) дізнайтеся, що можливо робити з QuestDB крок за кроком.
[Підручники:](https://questdb.io/tutorial/) вивчайте що можливо робити з QuestDB крок за кроком.

2022-10-20 14:40 UTC, eugenels commented on i18n/README.ua-ua.md
> +- [GitHub discussions:](https://github.com/questdb/questdb/discussions) пропонувати
- [GitHub discussions:](https://github.com/questdb/questdb/discussions) пропонуйте нові функції або демонструйте те, що ви створили.

2022-10-20 14:41 UTC, eugenels commented on i18n/README.ua-ua.md
> +  загальні способи усунення несправностей.
шукайте загальні способи усунення несправностей.

2022-10-20 14:42 UTC, eugenels commented on i18n/README.ua-ua.md
> +Ось результати high-cardinality бенчмаркінгу
Ось результати тесту продуктивності для даних великої розмірності Time Series Benchmark Suite що використовує cpu-only варіант з 6 паралельними задачами на AMD Ryzen 3970X:

2022-10-20 14:42 UTC, eugenels commented on i18n/README.ua-ua.md
> +У наведеній нижче таблиці показано час виконання запиту для мільярда рядків, які виконуються на `c5.metal` і використовує 16 із 96 доступних потоків:
У наведеній нижче таблиці показано час виконання запиту мільярда рядків, який виконуються на c5.metal
і використовує 16 із 96 доступних потоків:

2022-10-20 14:43 UTC, eugenels commented on i18n/README.ua-ua.md
> +## Порівняння QuestDB з іншими відкритими TSDB
Порівняння QuestDB із іншими TSDB з відкритим кодом.

2022-10-20 14:44 UTC, eugenels commented on i18n/README.ua-ua.md
> +Користувачі macOS можуть використовувати Homebrew:
Користувачі macOS можуть скористатися Homebrew:

2022-10-20 14:44 UTC, eugenels commented on i18n/README.ua-ua.md
> +[Сторінка завантажень QuestDB](https://questdb.io/get-questdb/) надає прямі
Сторінка завантажень QuestDB надає прямий доступ до інсталяційних файлів та містить інформацію про інші методи розгортання ПЗ.

2022-10-20 14:45 UTC, eugenels commented on i18n/README.ua-ua.md
> +Ми надаємо [живе демо](https://demo.questdb.io/) з останнім випуском QuestDB і зразки наборів даних:
Ми надаємо живе демо з останньою версією QuestDB та наступними зразками даних:

2022-10-20 14:45 UTC, eugenels commented on i18n/README.ua-ua.md
> +- 10 років поїздок на таксі з Нью-Йорка з 1,6 мільярда записей
10 років поїздок таксі Нью-Йорка (1,6 мільярда рядків)

2022-10-20 14:45 UTC, eugenels commented on i18n/README.ua-ua.md
> +- геолокації 250 тисяч унікальних кораблів
данні геолокації 250 тисяч унікальних кораблів

2022-10-20 14:47 UTC, eugenels commented on i18n/README.ua-ua.md
> +джерел з використанням об’єднань реляційних і часових рядів. QuestDB досягає високих результатів
QuestDB досягає високих результатів завдяки колонко-орієнтованій моделі зберігання данних,
масивно-паралельним обчисленням, використанню SIMD інструкцій, та застосуванню різноманітних технік низької затримки (low-latency).
Вся кодова база була створена з нуля із використанням мов програмування Java та С++,
не має зовнішніх залежностей, а також повністю незалежна від роботи автоматичного збирача сміття Java (GC-free).

2022-10-20 14:48 UTC, eugenels commented on i18n/README.ua-ua.md
> +QuestDB реалізує ANSI SQL із власними розширеннями, орієнтованої на
QuestDB реалізує мову ANSI SQL із власними розширеннями для ефективної обробки часових рядів.
Ці розширення значно спрощують обробку та аналіз декількох рядів за допомогою реляційних та часових операцій з'єднання таблиць.

2022-10-20 14:48 UTC, eugenels commented on i18n/README.ua-ua.md
> +QuestDB — це високопродуктивна база даних SQL з відкритим кодом для додатків у
QuestDB - це високопродуктивна SQL база даних із відкритим кодом,
оптимізована для застосування у сфері фінансових послуг, IoT, машинного навчання, DevOps та моніторингу.
Вона має можливості інтеграціі за допомогою протоколу PostgreSQL Wire,
прийому даних з високою пропускною здатністю та гнучкою схемою, використовуючи InfluxDB Line протокол,
а також REST API для запитів, імпорту та експорту даних.

2022-10-20 17:16 UTC, ideoma approved these changes

2022-10-20 17:24 UTC, ideoma commented on i18n/README.ua-ua.md
> +Ми завжди раді внеску в проект, незалежно від того, чи є він джерелами
done

2022-10-20 17:45 UTC, ideoma approved these changes

2022-10-20 17:54 UTC, bluestreak01 commented on i18n/README.ua-ua.md
> +Велика подяка цим чудовим людям, які зробили свій внесок у проєкт QuestDB
```suggestion
Велика подяка цим чудовим людям, які зробили свій внесок у проєкт
```

2022-10-20 22:44 UTC, ideoma approved these changes

2022-10-20 22:45 UTC, merged