docs(core): Spanish README translation
questdb/questdb pull request #2667
Opened 2022-10-21 09:28 UTC by marregui

Translated README to Spanish.

2022-10-21 10:09 UTC, bluestreak01 requested changes
thank you!

Can you please add a link to main readme ? so that you can see the translation on this URL: https://github.com/questdb/questdb/tree/ma/readme_que

2022-10-21 10:44 UTC, pswu11 commented
Hi @marregui we are doing slight improvements on readme in #2664

2022-10-21 10:48 UTC, marregui commented
thank you for the heads up @pswu11 , I will then wait for it those changes to be merged and I will diff/add to the Spanish version.

2022-10-22 20:10 UTC, bluestreak01 approved these changes

2022-10-22 20:46 UTC, merged