docs(core): Translated the readme to French and German
questdb/questdb pull request #2696
Opened 2022-10-27 19:46 UTC by VanshajPoonia

This Pull Request solves issues #2615 and #2616 

- I have translated the readme file into French and German.
- Added the functional links to the Japanese readme in all the other readme files as well.
- Naming of the readme done as per the guidelines.

2022-10-28 10:49 UTC, bluestreak01 requested changes

2022-10-28 13:03 UTC, VanshajPoonia commented on i18n/README-PT.md
> +[English](https://github.com/questdb/questdb) | [简体中文](README.zh-cn.md) | [繁體中文](README.zh-hk.md) | [العربية](README.ar-dz.md) | [Italiano](README.it-it.md) | [Українська](README.ua-ua.md) | [Español
I'm sorry! Actually, I didn't check the code and wrote it the way I pronounce it. I have updated the files accordingly.

2022-10-31 07:56 UTC, bluestreak01 commented
Are you a native German and French speaker?

2022-10-31 08:15 UTC, VanshajPoonia commented
> Are you a native German and French speaker?

I am not a native speaker. I've learnt French in school for 6 years (till class 10th; got 99/100 in the final exams).
I learnt German in 2020 from a YT channel called [Learn German with GermanPod101.com](https://youtube.com/c/Germanpod101) and also used Dictionary and Google translate for the parts which I wasn't sure about.
I know some other languages too but translations for most langauges that I know are already available.
Currently, I am looking forward to translate other docs too but I have my exams this month.

2022-10-31 17:53 UTC, bluestreak01 commented
thanks a lot! Our native French and German speakers are away right now. They will check your PR ASAP

2022-11-10 15:20 UTC, sandroqdb requested changes

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +relationale und Zeitreihen-Joins. Wir erreichen eine hohe Leistung, indem wir a
```suggestion
relationalen und Timeseries-Joins. Wir erreichen eine hohe Performance durch
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +Java und C++, ohne Abhängigkeiten und ohne Garbage Collection.
```suggestion
in Java und C++, ohne Abhängigkeiten und ohne Garbage Collection.
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +Wir stellen eine [Live-Demo](https://demo.questdb.io/) bereit, die mit den neuesten bereitgestellt wird
```suggestion
Wir stellen eine [Live-Demo](https://demo.questdb.io/) bereit, die mit den neuesten QuestDB Release
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +QuestDB-Release und Beispieldatensätze:
```suggestion
und Beispieldatensätze bereitgestellt wird:
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +Downloads für Binärdateien und enthält Details für andere Installationen und Bereitstellungen
```suggestion
Downloads für Binärdateien und enthält Details für andere Installationen und
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +- [InfluxDB line protocol](https://questdb.io/docs/reference/api/influxdb/) zum
```suggestion
- [InfluxDB line protocol](https://questdb.io/docs/reference/api/influxdb/) zur
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +Nachfolgend finden Sie unsere offiziellen InfluxDB-Leitungsprotokollclients für beliebte Programmierung
```suggestion
Nachfolgend finden Sie unsere offiziellen InfluxDB-Leitungsprotokollclients für beliebte Programmier-
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +vergleicht QuestDB übergreifend mit anderen Open-Source-Zeitreihendatenbanken
```suggestion
vergleicht QuestDB übergreifend mit anderen Open-Source-Timeseriesdatenbanken
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +Die folgende Tabelle zeigt die Abfrageausführungszeit von einer Milliarde Zeilen, die auf a ausgeführt werden
```suggestion
Die folgende Tabelle zeigt die Abfrageausführungszeit von einer Milliarde Zeilen, die auf einer
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +`c5.metal`-Instanz mit 16 der 96 verfügbaren Threads:
```suggestion
`c5.metal`-Instanz mit 16 der 96 verfügbaren Threads ausgefuehrt werden:
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +- [Produkt-Roadmap:](https://github.com/questdb/questdb/projects) sehen Sie sich unsere an
```suggestion
- [Produkt-Roadmap:](https://github.com/questdb/questdb/projects) sehen Sie sich unsere Roadmap an
```

2022-11-10 15:20 UTC, sandroqdb commented on i18n/README.de-de.md
> +- [Stack Overflow:](https://stackoverflow.com/questions/tagged/questdb) suchen
```suggestion
- [Stack Overflow:](https://stackoverflow.com/questions/tagged/questdb) suchen Sie
```

2022-11-10 16:12 UTC, sandroqdb requested changes

2022-11-10 16:12 UTC, sandroqdb commented on i18n/README-PT.md
> +[English](https://github.com/questdb/questdb) | [简体中文](README.zh-cn.md) | [繁體中文](README.zh-hk.md) | [العربية](README.ar-dz.md) | [Italiano](README.it-it.md) | [Українська](README.ua-ua.md) | [Español
```suggestion
[English](https://github.com/questdb/questdb) | [简体中文](README.zh-cn.md) | [繁體中文](README.zh-hk.md) | [العربية](README.ar-dz.md) | [Italiano](README.it-it.md) | [Українська](README.ua-ua.md) | [Español](README.es-es.md) | Português | [日本](./README.ja-ja.md) | [Français](./README.fr-fr.md) | [Deutsch](./README.de-de.md)
```

2022-11-10 16:21 UTC, VanshajPoonia commented on i18n/README-PT.md
> +[English](https://github.com/questdb/questdb) | [简体中文](README.zh-cn.md) | [繁體中文](README.zh-hk.md) | [العربية](README.ar-dz.md) | [Italiano](README.it-it.md) | [Українська](README.ua-ua.md) | [Español
I think I have already done this change

2022-11-11 11:47 UTC, bluestreak01 commented
would you mind resolving conflicts pls ?

2022-11-11 13:18 UTC, VanshajPoonia commented
> would you mind resolving conflicts pls ?

I'm sorry but I couldn't get which conflicts you are discussing.
I have committed to the suggestions that were made and visible to me.
I request you to please guide me a little

2022-11-15 11:09 UTC, sandroqdb requested changes
Requested 1 more change in row 108.

Besides that, the German translation looks good.

2022-11-15 11:09 UTC, sandroqdb commented on i18n/README.de-de.md
> +[Zeitreihen-Benchmark-Suite](https://questdb.io/blog/2021/06/16/high-cardinality-time-series-data-performance/)
```suggestion
[Timeseries-Benchmark-Suite](https://questdb.io/blog/2021/06/16/high-cardinality-time-series-data-performance/)
```

2022-11-15 11:09 UTC, sandroqdb commented on i18n/README.de-de.md
> +[Zeitreihen-Benchmark-Suite](https://questdb.io/blog/2021/06/16/high-cardinality-time-series-data-performance/)
Requested one more change for row 108. Besides that, the German translation looks good.

2023-03-27 16:16 UTC, bluestreak01 commented
there is no interest from @tris0laris

2023-03-27 16:16 UTC, closed without merging