fix(ilp): fix NPE in ILP ingestion during shutdown
questdb/questdb pull request #2770
Opened 2022-11-14 13:52 UTC by bziobrowski

Fixes NPE that happened while ingestion was doing on while qdb cloud instance was shutting down . 

I couldn't reproduce the issue so test is pretty hacky .

2022-11-14 23:40 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 13 / 13 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java|2|2|100.00%|

2022-11-15 10:18 UTC, bluestreak01 commented
@bziobrowski it would help review the PR if I could better understand the problem. May be inclusion on a log, stack trace in PR description would provide better context

2022-11-15 10:22 UTC, bluestreak01 requested changes

2022-11-15 10:22 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpReceiver.java
> +    private static final SchedulerInitalizer DEFAULT_INITIALIZER = LineTcpMeasurementScheduler::new;
do we defer constructor for testing only?

2022-11-15 10:24 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpReceiver.java
> +    @FunctionalInterface
the warnings can be fixed with method and interface visibility

2022-11-15 12:57 UTC, glasstiger commented on core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java
> +            throw CairoException.nonCritical().put("ILP listener is closing!");
if we cannot guarantee that IO jobs are stopped before writer jobs we could just drop the event, maybe print a warning to the log that we received something during shutdown and ignoring it.
however, i think we should be able to shut ILP down orderly.

2022-11-15 13:00 UTC, glasstiger commented on core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java
> +            throw CairoException.nonCritical().put("ILP listener is closing!");
maybe the shared pool was used and that mixed the ordering up?

2022-11-15 16:12 UTC, glasstiger commented on core/src/main/java/io/questdb/cutlass/line/tcp/LineTcpMeasurementEvent.java
> +            throw CairoException.nonCritical().put("ILP listener is closing!");
based on the attached logs i think the problem was that IO jobs did not have their dedicated pool and writer jobs were stopped before io jobs.
i guess we should document that if writer jobs have their own dedicated pool IO jobs should have their own too.

2022-11-17 08:57 UTC, bziobrowski commented
I reworked the PR to prevent dedicated & shared pool mixup in ilp config .

2022-11-17 09:00 UTC, bziobrowski commented on core/src/main/java/io/questdb/PropServerConfiguration.java
>                  }
Assuming enough cpus , default for io pool is higher than for writers so maybe prioritising number of dedicated io workers would make more sense ?

2022-11-17 09:27 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 12 / 12 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpReceiver.java|3|3|100.00%|

2022-11-17 14:49 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|8|8|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpWriterJob.java|1|1|100.00%|

2022-11-17 15:59 UTC, glasstiger approved these changes

2022-11-17 19:22 UTC, merged