fix(core): fix drop last partition async
questdb/questdb pull request #2802
Opened 2022-11-22 16:11 UTC by ideoma

Now that QuestDB allows to drop last (active) partition the Async `O3PurgePartitionJob` need to be adjusted to the use case and remove the directory from disk.

Also here added more logging on what `O3PurgePartitionJob` tries to delete and return error when partition DROP or DETACH with WHERE clause do not find suitable partition to detach to have same feedback as dropping with LISTing partition syntax.

2022-11-22 16:30 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 32 / 34 (94.12%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|

2022-11-22 19:11 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 32 / 34 (94.12%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|

2022-11-23 10:39 UTC, bluestreak01 requested changes

2022-11-23 10:39 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/O3PartitionPurgeTest.java
> +    @Test
file doesn't seem to be formatted correctly

2022-11-23 10:43 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/O3PartitionPurgeTest.java
> +    @Test
fixed in https://github.com/questdb/questdb/pull/2802/commits/e8545c9e00a159392d3674a6c27f8840075fb742

2022-11-23 10:43 UTC, bluestreak01 approved these changes

2022-11-23 13:25 UTC, bluestreak01 approved these changes

2022-11-23 13:42 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 44 / 46 (95.65%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/log/SyncLogger.java|0|1|00.00%|
|:large_blue_circle:|io/questdb/cairo/O3PartitionPurgeJob.java|17|18|94.44%|
|:large_blue_circle:|io/questdb/griffin/engine/table/LatestByAllIndexedRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/jit/CompiledFilterIRSerializer.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/DatabaseSnapshotAgent.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoEngine.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCompiler.java|13|13|100.00%|
|:large_blue_circle:|io/questdb/log/Logger.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableStructureAdapter.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/model/InsertModel.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/GenericRecordMetadata.java|3|3|100.00%|

2022-11-23 14:51 UTC, merged