fix(core): fix possible database crash when disk runs out of space
questdb/questdb pull request #2827
Opened 2022-11-28 22:00 UTC by bluestreak01

2022-11-28 22:35 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|2|2|100.00%|

2022-11-29 14:18 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|2|2|100.00%|

2022-11-30 00:56 UTC, ideoma approved these changes

2022-11-30 10:57 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|2|2|100.00%|

2022-11-30 11:08 UTC, amunra requested changes
* Some minor code clarity changes (optional)
* Missing error handling should be implemented.

2022-11-30 11:12 UTC, amunra commented
What would also be nice is to include logic to log the actual error in case `EXCEPTION_IN_PAGE_ERROR` happens again for a different reason.
See: https://devblogs.microsoft.com/oldnewthing/20120608-00/?p=7423

2022-11-30 17:57 UTC, bluestreak01 commented on core/src/main/c/freebsd/files.c
> +    gettimeofday(t, NULL);
good tip, thank you 👍 

fixed in https://github.com/questdb/questdb/pull/2827/commits/c29a957f3a4fd129da4addc65122a22e6598197c

2022-11-30 17:57 UTC, bluestreak01 commented on core/src/main/c/linux/files.c
> +    gettimeofday(t, NULL);
fixed in https://github.com/questdb/questdb/pull/2827/commits/c29a957f3a4fd129da4addc65122a22e6598197c

2022-11-30 17:57 UTC, bluestreak01 commented on core/src/main/c/linux/files.c
> +        unsigned long long k = ((unsigned long long) buf.f_bavail) * buf.f_bsize;
this seems to work on linux 👍

2022-11-30 17:58 UTC, bluestreak01 commented on core/src/main/c/windows/files.c
> +        int len = MultiByteToWideChar(CP_UTF8, 0, (LPCCH) lpszPath, -1, NULL, 0);
done in https://github.com/questdb/questdb/pull/2827/commits/c29a957f3a4fd129da4addc65122a22e6598197c

Also applied to all usages of `MultiByteToWideChar()`

2022-11-30 17:58 UTC, bluestreak01 commented on core/src/main/c/windows/files.c
> +        }
good spot, there was missing errno capture, fixed in https://github.com/questdb/questdb/pull/2827/commits/c29a957f3a4fd129da4addc65122a22e6598197c

2022-11-30 18:00 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/ColumnPurgeJobTest.java
> +        int deadline = Os.type == Os.WINDOWS ? 92 : 105;
on different platforms java calls different OS functions with different frequency in each test, this is just a nature of the beast. The change aims at failing the test in the same place as the code on master. The magic number `92` just happened to be the value of the counter in the place we want the fault to occur.

2022-11-30 18:14 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|2|2|100.00%|

2022-12-01 11:21 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/std/Files.java|2|3|66.67%|
|:large_blue_circle:|io/questdb/cairo/TableUtils.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/FilesFacadeImpl.java|2|2|100.00%|

2022-12-01 11:35 UTC, amunra approved these changes
Looking good!

2022-12-01 12:21 UTC, merged