fix(sql): fix sample by first/last keyed by non-symbol column
questdb/questdb pull request #2972
Opened 2023-02-07 13:53 UTC by bziobrowski

Fixes #2636 

PR improves logic of sample by factory selection .
It doesn't allow using SampleByFirstLastRecordCursorFactory when column list contains anything other than  : 
- first/last aggregates
- designated timestamp column
- filtered symbol column

2023-02-07 14:12 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 48 (97.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|31|32|96.88%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordComparatorCompiler.java|16|16|100.00%|

2023-02-08 09:28 UTC, ideoma submitted a review, later dismissed

2023-02-09 13:37 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 47 / 48 (97.92%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|31|32|96.88%|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordComparatorCompiler.java|16|16|100.00%|

2023-02-09 14:25 UTC, bluestreak01 requested changes

2023-02-09 14:25 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
> +                    return false;
this line is new and untested

2023-02-10 11:10 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 46 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordComparatorCompiler.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|30|30|100.00%|

2023-02-10 19:03 UTC, bziobrowski commented on core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
> +                    return false;
Removed in latest commit .

2023-02-15 00:03 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 46 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordComparatorCompiler.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|30|30|100.00%|

2023-02-21 19:24 UTC, bluestreak01 approved these changes

2023-02-22 16:39 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 46 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/orderby/RecordComparatorCompiler.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|30|30|100.00%|

2023-02-22 16:49 UTC, merged