fix(sql): allow bind variables in "string IN" values list
questdb/questdb pull request #3448
Opened 2023-06-06 12:59 UTC by bziobrowski

Fixes #3447

2023-06-06 13:22 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InStrFunctionFactory.java|25|25|100.00%|

2023-06-07 13:56 UTC, bluestreak01 requested changes

2023-06-08 09:00 UTC, puzpuzpuz submitted a review, later dismissed

2023-06-09 09:20 UTC, bziobrowski commented on core/src/test/java/io/questdb/test/cutlass/pgwire/PGJobContextTest.java
> +                stmt.setString(1, "Tuesday");
PR already had tests ensuring that deferred values works as expected.
Added tests with bind var changes in 9baf4f3a .

2023-06-09 09:40 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/InStrFunctionFactory.java|25|25|100.00%|

2023-06-09 12:13 UTC, bluestreak01 approved these changes

2023-06-09 12:13 UTC, merged