feat(sql): implement a function to convert two longs to UUID
questdb/questdb pull request #3559
Opened 2023-07-11 18:33 UTC by jerrinot

2023-07-11 18:55 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/uuid/LongsToUuidFunctionFactory.java|19|19|100.00%|

2023-07-12 08:11 UTC, jerrinot commented
documentation PR will follow upon merge (if that happens)

2023-07-12 17:22 UTC, bluestreak01 requested changes

2023-07-12 17:22 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/uuid/LongsToUuidFunctionFactory.java
> +            Misc.free(hi);
double-close

2023-07-13 07:23 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/uuid/LongsToUuidFunctionFactory.java|16|16|100.00%|

2023-07-19 10:19 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/uuid/LongsToUuidFunctionFactory.java|16|16|100.00%|

2023-07-19 16:02 UTC, merged