fix(http): min http works even when the main http server is disabled
questdb/questdb pull request #3732
Opened 2023-09-11 15:57 UTC by jerrinot

also introducing: `http.health.check.force.plaintext` to force plain HTTP for min.http server even when TLS for HTTP is enabled.

2023-09-13 13:31 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 67 / 68 (98.53%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|62|63|98.41%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/DefaultHttpServerConfiguration.java|1|1|100.00%|

2023-09-14 15:45 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 67 (98.51%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|59|60|98.33%|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/Services.java|2|2|100.00%|

2023-09-14 16:47 UTC, puzpuzpuz commented on core/src/main/java/io/questdb/PropServerConfiguration.java
> +//            if (httpServerEnabled) {
Looks like a leftover.

2023-09-14 16:47 UTC, puzpuzpuz commented on core/src/test/java/io/questdb/test/cutlass/http/HttpMinBootstrapTest.java
> +    public void testHttpServerEnabledMinStillWorking() throws Exception {
nit: the test name should be `testHttpServerDisabledMinServerStillWorking`

2023-09-15 10:54 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 67 (98.51%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|59|60|98.33%|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/Services.java|2|2|100.00%|

2023-09-15 11:38 UTC, puzpuzpuz approved these changes

2023-09-15 11:38 UTC, puzpuzpuz commented
Nice catch!

2023-09-15 11:56 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 66 / 67 (98.51%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|59|60|98.33%|
|:large_blue_circle:|io/questdb/DefaultFactoryProvider.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/HttpServer.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/FactoryProviderImpl.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/Services.java|2|2|100.00%|

2023-09-15 13:02 UTC, bluestreak01 requested changes

2023-09-15 13:02 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cutlass/Services.java
> +        final HttpServer server = new HttpServer(configuration, cairoEngine.getMessageBus(), metrics, workerPool, configuration.getFactoryProvider().getHttpSocketFactory());
this is formatting i am constantly undoing, would you mind changing?

it is either this, if call fits a line:

```java
void func(int a, int b, int c);
```
or 

```java
void func(
   int a,
   int b,
   int c
)
```

Not good:

```java
void func(int a, int b
   int c, int d);
```

2023-09-15 13:06 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cutlass/Services.java
> +        final HttpServer server = new HttpServer(configuration, cairoEngine.getMessageBus(), metrics, workerPool, configuration.getFactoryProvider().getHttpSocketFactory());
ooops, GH rendering issue, code is fine

2023-09-15 13:06 UTC, bluestreak01 approved these changes

2023-09-15 13:06 UTC, merged