fix(sql): fix empty result on second run of query with group by and limit
questdb/questdb pull request #3754
Opened 2023-09-15 14:40 UTC by bziobrowski

Fixes #3750

2023-09-15 22:35 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/VirtualFunctionSkewedSymbolRecordCursor.java|1|1|100.00%|

2023-09-16 00:06 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/VirtualFunctionSkewedSymbolRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|10|10|100.00%|

2023-09-18 08:58 UTC, bluestreak01 requested changes

2023-09-18 08:58 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlCodeGenerator.java
> +                        ArrayColumnTypes columnTypes = new ArrayColumnTypes();
creating new list seems unnecessary, if i make this change:
![image](https://github.com/questdb/questdb/assets/7276403/b7d3eb1a-acdf-45de-8595-b95f15a1a8d2)

tests pass also

2023-09-18 09:21 UTC, bluestreak01 approved these changes

2023-09-18 09:48 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/VirtualFunctionSkewedSymbolRecordCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlCodeGenerator.java|7|7|100.00%|

2023-09-18 10:05 UTC, merged