feat(core): add `mkdir.mode` permission config for detached partitions
questdb/questdb pull request #3818
Opened 2023-10-05 15:19 UTC by debanjanc01

Added an option to pass the mkdir mode detached partitions.
A new property key has been added: **cairo.sql.detached.mkdir.mode**
The default value is the same as for other mkdir modes, 509.

This closes [#3456](https://github.com/questdb/questdb/issues/3456)

2023-10-05 20:13 UTC, marregui requested changes
well thank you very much!

now for the fun part, the review. Just a minor request, open for discussion if you are keen. I left a comment. Everything else looks amazing.

2023-10-06 05:28 UTC, debanjanc01 commented on core/src/test/resources/server.conf
> +cairo.sql.detached.mkdir.mode=777
Hey @marregui the property name you've suggested makes more sense. I've updated it across all the changes. 
I've also added the new property to the distributable `server.conf` file.

All of the review changes are on a new commit. 
Let me know if you want me to squash the 2 commits into one. 👨‍💻

2023-10-06 07:04 UTC, marregui approved these changes
LGTM 

thank you for doing it. We need another pair of eyes and then we will be ready to merge!

the claim form is at the bottom of https://questdb.io/community/

2023-10-06 07:05 UTC, marregui commented
@debanjanc01 would you please be able to refresh your fork, pull master, merge master into your branch and then push on the PR again? thank you in advance.

2023-10-06 09:03 UTC, debanjanc01 commented
> @debanjanc01 would you please be able to refresh your fork, pull master, merge master into your branch and then push on the PR again? thank you in advance.

Done!

2023-10-06 10:04 UTC, merged

2023-10-06 10:19 UTC, marregui commented
Hi @debanjanc01 congratulations! it has been merged!, you are a questee.

If you found the experience fascinating, perhaps you would consider contributing more :D , these contributions are not only appreciated, they make the product better, for the whole wide world. Your name will be in the release notes. Now you get to pick anything from the issues list if you would like to. You could even decide to contribute something you would really like to have, and just need that little help to get it into the codebase, officially. Join the slack channel if you have not already, your experience is valuable there https://slack.questdb.io/ , we have 2.5k questees there already.

2023-10-06 14:31 UTC, debanjanc01 commented
Hey @marregui thanks! I'm thrilled to be a questee and would love to contribute more. 

I've joined the slack channel, thank you for sharing the link. Any pointers for going about in the community?

2023-10-06 20:52 UTC, marregui commented
community is friendly. We questees keep an eye and jump at responding when
we know the answer to some question.

Miguel Arregui
*audentes Fortuna iuvat* <http://uk.linkedin.com/in/marregui>


On Fri, 6 Oct 2023 at 16:31, Debanjan Choudhury ***@***.***>
wrote:

> Hey @marregui <https://github.com/marregui> thanks! I'm thrilled to be a
> questee and would love to contribute more.
>
> I've joined the slack channel, thank you for sharing the link. Any
> pointers for going about in the community?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/questdb/questdb/pull/3818#issuecomment-1750781368>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAB6ONFXRSOTXVJSMDLL4NDX6AI4BAVCNFSM6AAAAAA5UOBXMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJQG44DCMZWHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>