feat(ilp): make ILP over HTTP transactional for single table
questdb/questdb pull request #4110
Opened 2024-01-08 17:51 UTC by ideoma

2024-01-09 11:59 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/LineHttpProcessorState.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/WalTableUpdateDetails.java|1|1|100.00%|

2024-01-10 15:48 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cairo/wal/WalWriter.java
> +                            .$(", segTxn=").$(lastSegmentTxn)
nit: there is no reason not to align logging with variable names

2024-01-10 15:49 UTC, bluestreak01 requested changes

2024-01-10 15:49 UTC, bluestreak01 commented on core/src/main/java/io/questdb/cutlass/line/tcp/IlpWalAppender.java
> +//                                if (e.isTableDropped()) {
dead code

2024-01-10 16:31 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/LineHttpProcessorState.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/WalTableUpdateDetails.java|1|1|100.00%|

2024-01-11 19:44 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 25 / 25 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/LineTcpMeasurementScheduler.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/http/processors/LineHttpProcessorState.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/wal/WalWriter.java|16|16|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/TableUpdateDetails.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/line/tcp/WalTableUpdateDetails.java|1|1|100.00%|

2024-01-19 10:27 UTC, bluestreak01 approved these changes

2024-01-19 10:27 UTC, merged