chore(core): improve startup text
questdb/questdb pull request #4349
Opened 2024-03-28 18:31 UTC by mtopolnik

When started as a CLI command questdb or questdb.exe, we now show the Web Console URL and ILP client connection string.

We also tell whether HTTP or ILP is disabled, and show what config setting to change to enable it.

2024-03-28 19:10 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 38 / 39 (97.44%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-03-29 08:55 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 39 / 40 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|36|37|97.30%|
|:large_blue_circle:|io/questdb/ServerMain.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-03-29 10:21 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 39 / 40 (97.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|35|36|97.22%|
|:large_blue_circle:|io/questdb/ServerMain.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-03-29 11:38 UTC, bluestreak01 requested changes

2024-03-29 11:38 UTC, bluestreak01 commented on core/src/main/bin/questdb.sh
> +        ${JAVA} ${JAVA_OPTS} -Dhello-to-stderr -p ${JAVA_LIB} -m ${JAVA_MAIN} -d ${QDB_ROOT} ${QDB_OVERWRITE_PUBLIC} > ${QDB_LOG}/stdout-${DATE}.txt &
Ent version rust code is liable to produce critical messages into stderr. The stderr to stdout redirect was deliberate and should be kept. I realise this throws spanner in the works.

may be @eugenels or @amunra have ideas how to trap rust OOM erros and logs them to STDOUT?

2024-03-29 16:32 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 58 / 63 (92.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|46|51|90.20%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-04-03 19:08 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 58 / 63 (92.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|46|51|90.20%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-04-04 08:54 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 58 / 63 (92.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|46|51|90.20%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-04-04 13:27 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 58 / 63 (92.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|46|51|90.20%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-04-05 09:49 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 58 / 63 (92.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/Bootstrap.java|46|51|90.20%|
|:large_blue_circle:|io/questdb/ServerMain.java|10|10|100.00%|
|:large_blue_circle:|io/questdb/log/LogFactory.java|2|2|100.00%|

2024-04-11 11:48 UTC, bluestreak01 approved these changes

2024-04-11 14:50 UTC, merged