fix(sql): FILL(LINEAR) now supports ALIGN TO CALENDAR
questdb/questdb pull request #4392
Opened 2024-04-09 17:40 UTC by nwoolmer

Closes #4355 

This PR copies code used to initialise timestamp sampler from other FILL factories, into the interpolation factory. This means that it will support ALIGN TO CALENDAR, instead of always giving results for ALIGN TO FIRST OBSERVATION.

Confirmed with reporter that this gives the expected output.

2024-04-10 14:52 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 41 / 56 (73.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|41|56|73.21%|

2024-04-16 13:16 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 48 / 56 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|48|56|85.71%|

2024-04-17 08:16 UTC, jerrinot commented on core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
> +            if (!managedCursor.hasNext()) {
is this branch ever taken? if the manager cursor has no record then there is an early return right from `buildMap()` => `initTimestamps()` is not called at all? or do I miss a possible path?

2024-04-17 08:23 UTC, jerrinot commented on core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
> +        protected long nextDstUtc;
it looks this field is only assigned but never read? that's strange, isn't it? also: why is it protected and not private? some other fields could be private too.

2024-04-17 08:26 UTC, jerrinot commented on core/src/main/java/io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java
> +        protected long nextDstUtc;
it seems it's entirely missing code for DST adjustment. and equivalent of this https://github.com/questdb/questdb/blob/9683d03251aa6284bf8d2de0d6d60884a477d893/core/src/main/java/io/questdb/griffin/engine/groupby/AbstractNoRecordSampleByCursor.java#L141

2024-04-17 08:38 UTC, jerrinot requested changes
it looks to me like there are bugs due to DST transitions being ignored. 
happy to discuss it further, just give me a shout.

2024-04-18 11:25 UTC, jerrinot approved these changes
Thanks to @nwoolmer for both this PR and opening https://github.com/questdb/questdb/issues/4424 to clarify the remaining things. this PR already provides value as it is.

2024-04-18 12:09 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 48 / 54 (88.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|48|54|88.89%|

2024-04-18 18:17 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 48 / 54 (88.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/groupby/SampleByInterpolateRecordCursorFactory.java|48|54|88.89%|

2024-04-19 01:03 UTC, merged

2024-04-22 12:16 UTC, javier commented
Found a weird issue. Create a table using the SQL below and import the attached CSV. Then run this query

```
select timestamp, symbol,sum(price) 
from trades
where timestamp in '2024-04-22' 
sample by 1s fill(linear);
```
First thing I notice is that the timestamp order is not honored, and the first row is out of order, which does not happen with FILL(null). But weirder, if you re-execute the query, you get different results every time.


``` 
CREATE TABLE IF NOT EXISTS  'trades' (
  symbol SYMBOL capacity 256 CACHE,
  side SYMBOL capacity 256 CACHE,
  price DOUBLE,
  amount DOUBLE,
  timestamp TIMESTAMP
) timestamp (timestamp) PARTITION BY DAY WAL DEDUP UPSERT KEYS(timestamp, symbol, side);
```

[trades.csv](https://github.com/questdb/questdb/files/15062694/trades.csv)