fix(sql): split_part returning old data when no match is found
questdb/questdb pull request #4493
Opened 2024-05-10 10:44 UTC by nwoolmer

Closes https://github.com/questdb/questdb/issues/4489

Previously, the function could early return in the non-matching case without clearing the sink.

~The fix is to clear it at the top of the function.~

The fix is to split the impls so that the local sinks are cleared, and the remote sink not cleared, refactoring the original end-of-function check.

2024-05-10 11:43 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartVarcharFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactory.java|2|2|100.00%|

2024-05-12 09:09 UTC, bluestreak01 requested changes

2024-05-12 09:09 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactory.java
> +            if (clearSink && sink instanceof Mutable) {
we must not have instanceOf on the hot path

2024-05-13 15:45 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 13 / 17 (76.47%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactory.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartVarcharFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java|5|6|83.33%|

2024-05-14 20:38 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 13 / 17 (76.47%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactory.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartVarcharFunctionFactory.java|4|5|80.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java|5|6|83.33%|

2024-05-18 20:31 UTC, bluestreak01 approved these changes

2024-05-18 21:21 UTC, ideoma commented
#### [PR Coverage check]

:heart_eyes: **pass** : 52 / 74 (70.27%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartFunctionFactory.java|22|33|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartCharFunctionFactory.java|4|6|66.67%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/str/SplitPartVarcharFunctionFactory.java|26|35|74.29%|

2024-05-18 21:37 UTC, merged