bug(pgwire): Add BINARY_TYPE_VARCHAR in PgConnectionContext
questdb/questdb pull request #4685
Opened 2024-06-17 12:17 UTC by mtopolnik

We were missing the case when the binary flag was raised for varchar. It resulted in an empty response and broke the client.

2024-06-17 12:18 UTC, questdb-butler commented
<!--
  1 failure:  Please update the...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Please update the PR title to match this format:
`type(subType): description`

Where `type` is one of:
`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`, `ci`, `revert`

And: `subType` is one of:
`build`, `sql`, `log`, `mig`, `core`, `ilp`, `pgwire`, `http`, `conf`, `ui`, `wal`

For Example:

```
perf(sql): improve pattern matching performance for SELECT sub-queries
```
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7200390a7867f0b348dd48357cd39db5804baba2
</p>

2024-06-17 12:22 UTC, jerrinot requested changes
this sounds like something we should be able to test. 
there are pgwire tests exercising different protocol configs

2024-06-20 00:38 UTC, glasstiger approved these changes

2024-06-20 01:11 UTC, ideoma commented
#### [PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

2024-06-20 08:34 UTC, bluestreak01 approved these changes

2024-06-20 08:35 UTC, merged