feat(sql): add `DECLARE` keyword to support variable bindings
questdb/questdb pull request #5207
Opened 2024-11-28 16:12 UTC by nwoolmer

This PR introduces new syntax, `DECLARE`. This can be used to declare variables for re-use within your query, or subqueries.

A variable value is an expression, and most expressions in QuestDB are supported. For example:

```sql
DECLARE
    @a := 5,
    @b := 'foo',
    @c := dateadd('d', 1, now()),
    @d := @a + 4,
    @e := (select timestamp from trades LIMIT 1)
SELECT @a, @b, @c, @d, timestamp FROM @e
```

| 5 | foo | dateadd                     | column | timestamp                   |
|---|-----|-----------------------------|--------|-----------------------------|
| 5 | foo | 2024-12-07T12:42:24.691755Z | 9      | 2022-03-08T18:03:57.609765Z |

Fragments of statements are not supported. For example, this is **not** valid:

```sql
DECLARE
   @x := FROM trades
SELECT 5 @x
```

Todo:
- [x] Code
- [x] Docs - https://github.com/questdb/documentation/pull/86
     - [x] Mechanics
     - [x] Railroad
     - [x] Examples (WIP)
- [x] Syntax highlighting
    - [x] `DECLARE`, `:=` - https://github.com/questdb/sql-grammar/pull/35
    - [x] ~How do we handle `@variable` syntax?~ Handled courtesy of @goodroot

2024-12-04 17:47 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 185 / 196 (94.39%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|9|12|75.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|19|22|86.36%|
|:large_blue_circle:|io/questdb/griffin/RecursiveReplacingTreeTraversalAlgo.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|126|130|96.92%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|8|8|100.00%|

2024-12-05 16:32 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 185 / 196 (94.39%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|9|12|75.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|19|22|86.36%|
|:large_blue_circle:|io/questdb/griffin/RecursiveReplacingTreeTraversalAlgo.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|126|130|96.92%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|8|8|100.00%|

2024-12-05 18:45 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 185 / 196 (94.39%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|9|12|75.00%|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|19|22|86.36%|
|:large_blue_circle:|io/questdb/griffin/RecursiveReplacingTreeTraversalAlgo.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|126|130|96.92%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|8|8|100.00%|

2024-12-07 22:38 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/model/QueryModel.java
> +    public void setDecls(LowerCaseCharSequenceObjHashMap<ExpressionNode> decls) {
unused

2024-12-07 22:41 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlParser.java
> +    private ExecutionModel parseWith(GenericLexer lexer, SqlParserCallback sqlParserCallback,
nit: we need to avoid this type of code formatting, with multiple args on the same line while also using multi-line formatting

2024-12-07 22:43 UTC, bluestreak01 commented on core/src/test/java/io/questdb/test/griffin/SqlParserTest.java
> +    private static final String aaplDdl = "CREATE TABLE 'AAPL_orderbook' (\n" +
nit, please move DECLARE tests into separate class, SqlParserTest is 10k lines already and there is nothing it does that superclass cannot do

2025-01-01 02:23 UTC, bluestreak01 requested changes

2025-01-01 02:24 UTC, bluestreak01 commented
very good PR, please see main comment here: https://github.com/questdb/questdb/pull/5207#discussion_r1900304488 

multi-pass parsing will make the code less noisy

2025-01-06 08:37 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 191 / 200 (95.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|19|22|86.36%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/RecursiveReplacingTreeTraversalAlgo.java|13|14|92.86%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|132|136|97.06%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|8|8|100.00%|

2025-01-07 20:26 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 189 / 198 (95.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/ExpressionParser.java|19|22|86.36%|
|:large_blue_circle:|io/questdb/griffin/model/QueryModel.java|9|10|90.00%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|142|147|96.60%|
|:large_blue_circle:|io/questdb/griffin/FunctionParser.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/OperatorExpression.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlException.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|7|7|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlKeywords.java|8|8|100.00%|

2025-01-07 20:44 UTC, bluestreak01 approved these changes

2025-01-07 21:23 UTC, merged