feat(sql): introduce EXISTS(sub-query) predicate
questdb/questdb pull request #5240
Opened 2024-12-11 14:31 UTC by jerrinot

This allows queries such as
```sql
SELECT EXISTS (
SELECT table_schema, table_name
FROM information_schema.tables
WHERE TRUE
  AND table_schema = 'public'
  AND table_name = 'r_demo_copy'
);
```
RPostgres uses this specific query to check the existence of a table during 
`dbWriteTable(con, Id(schema = "public", table = "r_demo_copy"), dbReadTable(con, Id(schema = "public", table = "r_demo")))`

**Limitation:** The subquery inside `exists()` must be uncorrelated with the outer query. 
In other words: It must not reference any column defined outside of the subquery in `exists()`.

Also: SqlParser now consistently removes public schema from table names. 
Previously, this was done for SELECT queries only. 

This change means queries like

```sql
INSERT INTO "public"."r_demo_copy"
  ("ticker", "price", "ts")
VALUES
  ('EUR', 100.1::float8, '2024-12-11 09:34:38.016566'::timestamp);
```

or
```sql
CREATE TABLE "public"."r_demo_copy" (
  "ticker" TEXT,
  "price" DOUBLE PRECISION,
  "ts" TIMESTAMP
);
```
now work.

2024-12-11 14:33 UTC, jerrinot commented
related RPostgres issue: https://github.com/r-dbi/RPostgres/issues/482

2024-12-11 16:37 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 42 (95.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|25|27|92.59%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/ExistsFunctionFactory.java|15|15|100.00%|

2024-12-17 09:52 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 42 (95.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|25|27|92.59%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/ExistsFunctionFactory.java|15|15|100.00%|

2024-12-18 13:16 UTC, ideoma commented
Is it correct to assume that subquery in the EXISTS must be non-correlated?

2024-12-20 15:21 UTC, jerrinot commented
@ideoma wdyt now?

2024-12-20 16:50 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 40 / 42 (95.24%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|25|27|92.59%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/ExistsFunctionFactory.java|15|15|100.00%|

2025-01-01 00:38 UTC, bluestreak01 requested changes

2025-01-01 00:38 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/SqlParser.java
> +        tok = parseTableNameSansPublicSchema(lexer, "UPDATE, WITH or table name expected");
this is very aggressive approach. Virtually everywhere we use to just get a token, now there is mostly redundant and quite unreadable table name parsing

2025-01-02 09:09 UTC, jerrinot commented on core/src/main/java/io/questdb/griffin/SqlParser.java
> +        tok = parseTableNameSansPublicSchema(lexer, "UPDATE, WITH or table name expected");
ok, there are ways to tone it down a bit. let me have a look if that results in readability improvements.

2025-01-02 10:54 UTC, jerrinot commented on core/src/main/java/io/questdb/griffin/SqlParser.java
> +        tok = parseTableNameSansPublicSchema(lexer, "UPDATE, WITH or table name expected");
I changed it so the stripping is only applied when we do actually expect a table name. wdyt?

2025-01-02 13:52 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 46 / 46 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|31|31|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/ExistsFunctionFactory.java|15|15|100.00%|

2025-01-02 16:08 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 91 / 92 (98.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|41|42|97.62%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|35|35|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/ExistsFunctionFactory.java|15|15|100.00%|

2025-01-22 18:33 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 91 / 92 (98.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|41|42|97.62%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|35|35|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/ExistsFunctionFactory.java|15|15|100.00%|

2025-02-04 18:19 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 91 / 92 (98.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/SqlOptimiser.java|41|42|97.62%|
|:large_blue_circle:|io/questdb/griffin/SqlParser.java|35|35|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bool/ExistsFunctionFactory.java|15|15|100.00%|

2025-03-24 12:19 UTC, closed without merging