feat(sql): multi-threaded read_parquet() execution
questdb/questdb pull request #5256
Opened 2024-12-17 13:40 UTC by puzpuzpuz

Closes #5250

2025-01-02 10:07 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 113 / 126 (89.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameRecordCursorFactory.java|20|23|86.96%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java|74|84|88.10%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/PageFrameRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

2025-01-02 10:33 UTC, puzpuzpuz commented
@nwoolmer the PR should be ready for review now. PTAL

2025-01-13 16:52 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 113 / 126 (89.68%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameRecordCursorFactory.java|20|23|86.96%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java|74|84|88.10%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/PageFrameRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

2025-01-14 09:39 UTC, ideoma submitted a review, later dismissed

2025-01-14 10:04 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 128 / 141 (90.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameRecordCursorFactory.java|20|23|86.96%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java|74|84|88.10%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/PageFrameRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

2025-01-14 10:40 UTC, bluestreak01 requested changes
still under review

2025-01-14 11:45 UTC, mtopolnik commented on core/src/main/java/io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java
> +        for (int i = 0, n = metadata.getColumnCount(); i < n; i++) {
Is there a reason why this loop's body can't be integrated into the loop above?

2025-01-14 11:45 UTC, mtopolnik commented on core/src/main/java/io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java
> +        return metadataType == ColumnType.VARCHAR && decoderType == ColumnType.SYMBOL;
It would be easire for me to understand the code if this method was inlined. The name is more confusing than the condition it checks.

2025-01-14 12:15 UTC, puzpuzpuz commented on core/src/main/java/io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java
> +        for (int i = 0, n = metadata.getColumnCount(); i < n; i++) {
Simplified the loop and reused code between single-threaded cursor and this one in 91ebac0a0c4cc4970f72e9aeef0ed65952ee71b8

2025-01-14 12:15 UTC, puzpuzpuz commented on core/src/main/java/io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java
> +        return metadataType == ColumnType.VARCHAR && decoderType == ColumnType.SYMBOL;
Inlined in 91ebac0a0c4cc4970f72e9aeef0ed65952ee71b8

2025-01-14 12:18 UTC, mtopolnik approved these changes

2025-01-14 17:22 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 124 / 137 (90.51%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetRecordCursor.java|9|11|81.82%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameRecordCursorFactory.java|20|23|86.96%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java|61|69|88.41%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/PageFrameRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|

2025-01-15 14:23 UTC, bluestreak01 approved these changes

2025-01-15 14:59 UTC, bluestreak01 approved these changes

2025-01-15 15:57 UTC, glasstiger commented
#### [PR Coverage check]

:heart_eyes: **pass** : 145 / 164 (88.41%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|io/questdb/cairo/vm/MemoryPARWImpl.java|0|6|00.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameRecordCursorFactory.java|20|23|86.96%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetRecordCursor.java|15|17|88.24%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetPageFrameCursor.java|61|69|88.41%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/modern/PGPipelineEntry.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropServerConfiguration.java|3|3|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FwdTableReaderPageFrameCursor.java|4|4|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/table/ReadParquetFunctionFactory.java|5|5|100.00%|
|:large_blue_circle:|io/questdb/cairo/sql/PageFrameMemoryRecord.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/vm/api/MemoryCR.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/bind/Long256BindVariable.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cairo/DefaultCairoConfiguration.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/cast/CastSymbolToLong256FunctionFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/PropertyKey.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/PageFrameRecordCursorFactory.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/BwdTableReaderPageFrameCursor.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/functions/conditional/CoalesceFunctionFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/cairo/TableWriter.java|15|15|100.00%|
|:large_blue_circle:|io/questdb/griffin/engine/table/FilterOnExcludedValuesRecordCursorFactory.java|2|2|100.00%|
|:large_blue_circle:|io/questdb/std/Numbers.java|6|6|100.00%|
|:large_blue_circle:|io/questdb/cairo/CairoConfigurationWrapper.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/cutlass/pgwire/PGConnectionContext.java|1|1|100.00%|
|:large_blue_circle:|io/questdb/griffin/SqlUtil.java|1|1|100.00%|

2025-01-15 16:03 UTC, merged