chore(griffin) - various view and functions needed for Kafka metadata queries
questdb/questdb pull request #697
Opened 2020-11-12 14:02 UTC by jaugsburger

2020-11-12 14:12 UTC, bluestreak01 requested changes

2020-11-12 14:12 UTC, bluestreak01 commented on core/src/test/java/io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactoryTest.java
> +    public void testSecondKafkaMetadataQuery() throws Exception {
the goal of the SQL is to enumerate table columns like PG does

```
 nspname | relname  |  attname   | atttypid | attnotnull | atttypmod | attlen | typtypmod | attnum | attidentity | adsrc | description | typbasetype | typtype
---------+----------+------------+----------+------------+-----------+--------+-----------+--------+-------------+-------+-------------+-------------+---------
 public  | po_items | po_no      |       23 | t          |        -1 |      4 |        -1 |      1 |             |       |             |           0 | b
 public  | po_items | item_no    |       23 | t          |        -1 |      4 |        -1 |      2 |             |       |             |           0 | b
 public  | po_items | product_no |       23 | f          |        -1 |      4 |        -1 |      3 |             |       |             |           0 | b
 public  | po_items | qty        |       23 | f          |        -1 |      4 |        -1 |      4 |             |       |             |           0 | b
 public  | po_items | net_price  |     1700 | f          |        -1 |     -1 |        -1 |      5 |             |       |             |           0 | b
(5 rows)
```

2020-11-12 14:12 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/catalogue/AttributeCatalogueFunctionFactory.java
> +        metadata.add(new TableColumnMetadata("atttypid", ColumnType.INT, null));
the aim of the SQL is to enum columns. Having constant 0 out of the field isn't going to work

2020-11-16 10:13 UTC, bluestreak01 requested changes

2020-11-16 10:13 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/catalogue/DescriptionCatalogueFunctionFactory.java
> +                return columnNumber == 0 ? "table" : "column";
use sparse array

2020-11-16 10:13 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/catalogue/PrefixedTypeCatalogueFunctionFactory.java
> +    public Function newInstance(ObjList<Function> args, int position, CairoConfiguration configuration) {
check if base type does the same and remove if duplicate

2020-11-16 10:13 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TypeCatalogueCursor.java
> +            return col == 0 ? PG_TYPE_OIDS.get(row) : col == 4 ? PgOIDs.PG_PUBLIC_OID : 0;
use sparse array

2020-11-16 10:13 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TypeCatalogueCursor.java
> +            return PG_TYPE_TO_NAME.get(PG_TYPE_OIDS.get(row));
`PG_TYPE_TO_NAME` should be an array (dense)

2020-11-16 10:13 UTC, bluestreak01 commented on core/src/main/java/io/questdb/griffin/engine/functions/catalogue/TypeCatalogueFunctionFactory.java
>  public class TypeCatalogueFunctionFactory implements FunctionFactory {
check if this factory overrides `isCursor()`

isCursor must return `true` for all factories that return cursor instance

2020-11-16 10:16 UTC, tuanggo approved these changes

2020-11-17 12:58 UTC, bluestreak01 approved these changes

2020-11-17 12:58 UTC, merged