Fix failed to import single-column CSV
questdb/questdb pull request #729
Opened 2020-12-18 05:55 UTC by tonytamwk

- fixed #547

2020-12-18 05:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb?pullRequest=729) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb?pullRequest=729) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb?pullRequest=729) it.</sub>

2020-12-18 13:32 UTC, bluestreak01 requested changes
Thank you Tony!

We have bunch of test for text loader in https://github.com/questdb/questdb/blob/master/core/src/test/java/io/questdb/cutlass/text/TextLoaderTest.java

Do you mind adding one for the issue you fixed?

2020-12-19 15:35 UTC, tonytamwk commented
> Thank you Tony!
> 
> We have bunch of test for text loader in https://github.com/questdb/questdb/blob/master/core/src/test/java/io/questdb/cutlass/text/TextLoaderTest.java
> 
> Do you mind adding one for the issue you fixed?

Sure and done

2020-12-20 20:24 UTC, bluestreak01 commented
The fix and test look good, thanks once again! Do you also mind signing CLA pls, otherwise merging PR is blocked

2020-12-22 00:06 UTC, bluestreak01 approved these changes

2020-12-22 00:07 UTC, merged