fix(jvm): Eliminate the need to use '--add-exports' VM option
questdb/questdb pull request #857
Opened 2021-03-11 22:06 UTC by the-sheev

Tested on Java 11 and Java 16.

2021-03-14 21:54 UTC, bluestreak01 requested changes
perhaps we should delete windows dockerfile to avoid confusion

2021-03-14 22:48 UTC, the-sheev commented on core/Dockerfile-windows
> -FROM mcr.microsoft.com/windows/nanoserver:1903
It still creates the image without build artifacts. I replaced it with the line above.

2021-03-15 14:42 UTC, bluestreak01 requested changes

2021-03-15 14:42 UTC, bluestreak01 commented on win64svc/src/questdb.c
>                        " -XX:+UseParallelOldGC"
This flag does not work on JDK 16:

![image](https://user-images.githubusercontent.com/7276403/111170965-6329ac80-859c-11eb-8960-1820c34555e1.png)

2021-03-15 14:42 UTC, bluestreak01 commented on win64svc/src/questdb.c
>      LPCSTR javaOpts = "-XX:+UnlockExperimentalVMOptions"
we need to compile the executable, it is checked into `git` repo

2021-03-15 14:42 UTC, bluestreak01 commented on core/Dockerfile
> +FROM openjdk:16-alpine
using generic image overinflates the image size:

![image](https://user-images.githubusercontent.com/7276403/111171183-95d3a500-859c-11eb-8625-aaef03c4a70f.png)

2021-03-15 14:42 UTC, bluestreak01 commented on core/Dockerfile
> -CMD ["/app/bin/java", "--add-exports", "java.base/jdk.internal.math=io.questdb", "-m", "io.questdb/io.questdb.ServerMain", "-d", "/root/.questdb", "-f"]
we need to use "RT" binary to keep image size small

2021-03-15 23:53 UTC, the-sheev commented
I used `--release` to cross-compile with Maven to use Java 16 to run `jlink` (otherwise, compilation against JDK 16 fails). Unfortunately, `--release` does not work with `--add-exports`, so we will need to eliminate usages of `FDBigInteger` before we can merge this pull request (related: #862).

2021-03-17 10:30 UTC, bluestreak01 approved these changes

2021-03-17 11:56 UTC, merged